export const SET_LOADING = "SET_LOADING";
export const GET_CARS = "GET_CARS";
export const GET_CAR = "GET_CAR";
export const FILTER_CARS = "FILTER_CARS";
export const CAR_ERROR = "CAR_ERROR";

export const ADD_FILTER = "ADD_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";
export const ADD_LOCATION_FILTER = "ADD_LOCATION_FILTER";
export const REMOVE_LOCATION_FILTER = "REMOVE_LOCATION_FILTER";
export const ADD_TIME_FILTER = "ADD_TIME_FILTER";

export const ADD_ERROR_MESSAGE = "ADD_ERROR_MESSAGE";
export const REMOVE_ERROR_MESSAGE = "REMOVE_ERROR_MESSAGE";

export const GET_RESERVATIONS = "GET_RESERVATIONS";
export const GET_BACK_RESERVATIONS = "GET_BACK_RESERVATIONS";
export const RESERVATION_ERROR = "RESERVATION_ERROR";
export const RESERVATION_UPDATE = "RESERVATION_UPDATE";

export const ADD_CREDENTIALS = "ADD_CREDENTIALS";
export const REMOVE_CREDENTIALS = "REMOVE_CREDENTIALS";
